# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_sayi1 = QtWidgets.QLabel(self.centralwidget)
        self.txt_sayi1.setGeometry(QtCore.QRect(10, 30, 81, 41))
        self.txt_sayi1.setObjectName("txt_sayi1")
        self.txt_sayi2 = QtWidgets.QLabel(self.centralwidget)
        self.txt_sayi2.setGeometry(QtCore.QRect(10, 80, 47, 13))
        self.txt_sayi2.setObjectName("txt_sayi2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 40, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 80, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.btn_topla = QtWidgets.QPushButton(self.centralwidget)
        self.btn_topla.setGeometry(QtCore.QRect(20, 130, 75, 23))
        self.btn_topla.setObjectName("btn_topla")
        self.btn_cikar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cikar.setGeometry(QtCore.QRect(110, 130, 75, 23))
        self.btn_cikar.setObjectName("btn_cikar")
        self.btn_carp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_carp.setGeometry(QtCore.QRect(20, 170, 75, 23))
        self.btn_carp.setObjectName("btn_carp")
        self.btn_bol = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bol.setGeometry(QtCore.QRect(110, 170, 75, 23))
        self.btn_bol.setObjectName("btn_bol")
        self.btn_ort = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ort.setGeometry(QtCore.QRect(60, 210, 75, 23))
        self.btn_ort.setObjectName("btn_ort")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 300, 47, 13))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_sayi1.setText(_translate("MainWindow", "Sayı :"))
        self.txt_sayi2.setText(_translate("MainWindow", "Sayı :"))
        self.btn_topla.setText(_translate("MainWindow", "Toplam"))
        self.btn_cikar.setText(_translate("MainWindow", "Çıkarma"))
        self.btn_carp.setText(_translate("MainWindow", "Çarpma"))
        self.btn_bol.setText(_translate("MainWindow", "Bölme"))
        self.btn_ort.setText(_translate("MainWindow", "Ortlama"))
        self.label.setText(_translate("MainWindow", "Sonuc:"))
