# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RadioButtonForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 160, 88))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioAlmanya = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioAlmanya.setObjectName("radioAlmanya")
        self.gridLayout.addWidget(self.radioAlmanya, 2, 0, 1, 1)
        self.radioIspanya = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioIspanya.setObjectName("radioIspanya")
        self.gridLayout.addWidget(self.radioIspanya, 0, 0, 1, 1)
        self.radioTurkiye = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioTurkiye.setObjectName("radioTurkiye")
        self.gridLayout.addWidget(self.radioTurkiye, 1, 0, 1, 1)
        self.radioRusya = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioRusya.setObjectName("radioRusya")
        self.gridLayout.addWidget(self.radioRusya, 3, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 120, 160, 88))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lise = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.lise.setObjectName("lise")
        self.gridLayout_2.addWidget(self.lise, 1, 0, 1, 1)
        self.ilkokul = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.ilkokul.setObjectName("ilkokul")
        self.gridLayout_2.addWidget(self.ilkokul, 0, 0, 1, 1)
        self.universite = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.universite.setObjectName("universite")
        self.gridLayout_2.addWidget(self.universite, 2, 0, 1, 1)
        self.yuksekLisans = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.yuksekLisans.setObjectName("yuksekLisans")
        self.gridLayout_2.addWidget(self.yuksekLisans, 3, 0, 1, 1)
        self.lblUlke = QtWidgets.QLabel(self.centralwidget)
        self.lblUlke.setGeometry(QtCore.QRect(20, 230, 47, 13))
        self.lblUlke.setObjectName("lblUlke")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 260, 47, 13))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 300, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 300, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioAlmanya.setText(_translate("MainWindow", "Almanya"))
        self.radioIspanya.setText(_translate("MainWindow", "İspanya"))
        self.radioTurkiye.setText(_translate("MainWindow", "Türkiye"))
        self.radioRusya.setText(_translate("MainWindow", "Rusya"))
        self.lise.setText(_translate("MainWindow", "Lise"))
        self.ilkokul.setText(_translate("MainWindow", "İlkOkul"))
        self.universite.setText(_translate("MainWindow", "Üniversite"))
        self.yuksekLisans.setText(_translate("MainWindow", "Yüksek Lisans"))
        self.lblUlke.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "Ülke Seçimi"))
        self.pushButton_2.setText(_translate("MainWindow", "Eğitim Seçimi"))
